# Generated by Django 4.1 on 2022-09-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlescope_tag_articlescope_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='article',
        ),
    ]
